name: .NET

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.101
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Release --no-restore -o ./publish/LambdaHelloWorld
      
    - name: Archive project
      run: zip -j ./publish/LambdaHelloWorld.zip ./publish/LambdaHelloWorld/*

    - uses: ncipollo/release-action@v1
      with:
        artifacts: ./publish/LambdaHelloWorld.zip
        draft: true
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
