name: Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-ecs-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.101
      env:
        DOTNET_INSTALL_DIR: "/home/runner/.dotnet"
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Test sudo
      run: |
        sudo apt update
        sudo apt install nano -y
